INSERT INTO dicionario (palavra, significado) VALUES
('Weita', 'Pássaro'), 
('Urukut', 'Coruja'), 
('Úre', 'Jacamim'),
('Urit’i', 'Inambú'),
('Weita hít', 'Passarinho'),
('Wiawu', 'Mutum'),
('Awi’a', 'Abelha'),
('Ape’i/arawe', 'Barata'),
('Gap', 'Caba (pequeno inseto que voa, sua ferroada dolorida)'),
('Gyp', 'Piolho'), 
('Jug', 'Pulga'),
('Kiã', 'Aranha'),
('Kíwa', 'Tapecuim (pequeno inseto que voa, serve para alimentação dos sateré)'),
('Karawót', 'Cigarra'),
('Mantéru', 'Vaga-lume (é um pequeno inseto que tem luz própria, que voa, anda durante à noite. Este inseto não pode ser pegado com a mão. A pessoa que pega segundo os mais velhos, terá coisas fáceis de quebrar)'),
('Morope’i/morepe’i', 'Borboleta'),
('Mokag', 'Louva-a-deus'),
('Pohit', 'Gafanhoto'), 
('Sapót', 'Escorpião'),
('Sári', 'Formiga'), 
('Sahai', 'Saúva-taia (pequeno inseto comestível, sua cabeça contém tipo uma pimenta, serve para tomar com xibé)'), 
('Úwi', 'Minhoca'), 
('Ut', 'Lagarto'),
('Upi’u', 'Maruim (insetos que gostam de incomodar caçadores de noite durante à espera de caça)'), 
('We’ehog', 'Maniwara (inseto comestível com farinha molhada'),
('Wanti’u', 'Carapanã'), 
('Watyama', 'Tucandeira (inseto com ferroada que é usado para o ritual da tucandeira pelos sateré)'), 
('Wáru’i', 'Mucuim'),
('Aware', 'Cachorro (serve para vigiar à casa como também para caçar animais)'), 
('Hamaut asuwai', 'Porco suíno'),
('Pisana', 'Gato'),
('Piku-piku', 'Pinto'), 
('Waipaka wáry’i', 'Galinha'), 
('Waipaka pa’aiat', 'Galo'), 
('Wewato ahup', 'Boi'), 
('Ypéka', 'Pato');

