
INSERT INTO dicionario (palavra, significado) VALUES
('Ihot’ok', 'Bom dia'),
('Heika’at', 'Boa tarde'),
('Wantym', 'Boa noite'),
('Meiko ira’yn aru', 'Até já/mais!'),
('Mogki’ite ira’yn aru', 'Até amanhã.'),
('Hay', 'Olá/Oi!'),
('Waku sese', 'Muito obrigado.'),
('Meke arekosap/mekepuo aru', 'Com licença.'),
('Yt kat hap hin’i/yt kat hap’i', 'de nada!'),
('Waku?', 'Tudo bem?'),
('Waku', 'Bem/Bom'),
('Waku sese eriot!', 'Seja bem-vindo!'),
('Akag', 'Cabeça'),
('Asap', 'Cabelo'),
('Ape', 'Costa'),
('Ampy', 'Nariz'),
('Ahape', 'Orelha'),
('Anti’ypy', 'Ombro'),
('Ahit', 'Pênis'),
('Ikag', 'Osso'),
('Jaig', 'Dente'),
('Jun', 'Fezes'),
('Junmy’a', 'Barriga'),
('Kag’oktu', 'Perna'),
('Moti’a', 'Peito'),
('Mu’uja', 'Dedo'),
('My’a', 'Figado'),
('My’akag’a', 'Joelho'),
('Mo', 'Mão'),
('My', 'pé'),
('Myawa', 'Sola do pé'),
('My’okpe', 'pé'),
('Mopy’akag’a', 'Cotovelo'),
('My’ampát', 'Articulação do joelho'),
('Myrum’a', 'Umbigo'),
('Nywa', 'Queixo'),
('Oktu/uptu', 'Coxa'),
('Okpy', 'nus'),
('Sempe', 'Beiço'),
('Setu’a', 'Nádegas'),
('Seha', 'Olho'),
('MÍt Pít Ekaria’i', 'Anatomia do Corpo Humano 4'),
('Sewa', 'Rosto'),
('Segku', 'Língua'),
('Si’ã', 'Vagina'),
('Wẽ', 'Boca'),
('Wesap', 'Bogode'),
('Wegkot’a', 'Bochecha'),
('Watu’a', 'Testa'),
('Yke', 'Braço'),
('Akuri', 'Cutia'),
('Awahuru', 'Cachorro do mato'),
('Awyky', 'Guariba'),
('Awyato', 'Onça'),
('Ariukere', 'Preguiça'),
('Hapiri', 'Rato'),
('Hamaut', 'Porco'),
('Himpa', 'Tamanduá bandeira'),
('Hami’ῖ', 'Xauim'),
('Hanu’án', 'Macaco prego'),
('Iakare', 'Jacaré'),
('Moi', 'Cobra'),
('Pay', 'Paca'),
('Sahu', 'Tatu'),
('Wewato', 'Anta'),
('Wawori', 'Jabuti'),
('Wakiu’i wato', 'Macaco velho');
